### ISSUE TITLE
never-ending todo list

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/hafas-client#9]
- [ ] https://github.com/search?l=JavaScript&q=user%3Aderhuerst+hafas-client&type=Code
- [ ] derhuerst/vbb-hafas@74680b7
- [ ] public-transport/friendly-public-transport-format#27
- [ ] `locL[].meta` & `locL[].isMainMast` & `locL[].mMastLocX`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-02-semi-accessible-http-L148
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-02-semi-accessible-http-L150
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-02-semi-accessible-http-L166
- [ ] DB: parse tickets
- [ ] journey legs: duration for better UX?
- [ ] luxon -> date-fns ?
- [ ] journey leg `arrivalDelay`, `arrivalPlatform`
	- https://github.com/derhuerst/vbb-rest/blob/4332462b8a78092c8ec60388888d2a2793d86c6d/lib/departures.js#L4VBB
- [ ] [breaking] rename `opt.passedStations` to `stopovers`?
- [ ] [breaking] rename `dep.journeyId` -> `dep.journeyPartId`
- [ ] [breaking] remove or rename `line.class`
- [ ] [breaking] `nearby`: `location` obj as single arg
- [ ] [breaking] `journeys`: make default `accessibility` `null`
- [ ] #3 1.16 `mic`/`mac` https://github.com/derhuerst/hafas-client/issues/3
- [ ] "Haltestellen in der Umgebung berücksichtigen"
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L47
- [ ] `prodL[].pid`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L116
- [ ] `prodL[].prodCtx.matchId`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L127
- [ ] `prodL[].prodCtx.admin`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L133
- [ ] `prodL[].stat`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L135-L171
- [ ] `prodL[].stat.cncl`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-04-radar-http-L1604
- [ ] `(secL[].)jny.stopL[].type`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L662
himL
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L480-L509
- [ ] `secL[].msgL`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L746-L781
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-01-take-close-stations-into-account-http-L903-L918
secL[].minChg
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-02-semi-accessible-http-L1160
- [ ] `(secL[].)jny.stopL[].dPlatfR` & `(secL[].)jny.stopL[].aPlatfR`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-04-radar-http-L3178
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-04-radar-http-L3185
- [ ] `(secL[].)jny.stopL[].dInS` & `(secL[].)jny.stopL[].dOutS`
	- https://gist.github.com/derhuerst/6ba0fdd6dc0d940c594f28cde067ad22#file-04-radar-http-L3190

**Comment by derhuerst** [comment]
more from [`vbb-hafas`](https://github.com/derhuerst/vbb-hafas#vbb-hafas):

- [ ] `journeys` input: adapt to [FPTF](todo)!
- [ ] rename `journey.parts` -> `journey.legs`, `/s/parts/legs`
- [ ] refactor station name shortening (see `spot shorten`) ?

**Comment by derhuerst** [comment]
more from [`vbb-hafas`](https://github.com/derhuerst/vbb-hafas#vbb-hafas):

- [ ] `journeys` input: adapt to [FPTF](https://github.com/public-transport/friendly-public-transport-format#friendly-public-transport-format-fptf)!
- [ ] `journey.parts` -> `journey.legs`, /s/parts/legs
- [ ] refactor station name shortening (see `spot shorten`)

**Comment by derhuerst** [comment]
more from [`db-hafas`](https://github.com/derhuerst/db-hafas#db-hafas):

- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_pois-properties
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_products-properties
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_rt-properties
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_sotchange-properties
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_texte_de-properties-L349-L376
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_texte_de-properties-L380-L390
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_texte_de-properties-L397-L414
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_texte_de-properties-L607-L633
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_texte_de-properties-L699-L722
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-verbuende-json
- [ ] https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-tech-properties
- [ ] https://reiseauskunft.bahn.de/addons/verbuende.json
- [ ] http://gishost-osm.hacon.de/res/networkmaps.json

**Comment by derhuerst** [comment]
- [ ] https://github.com/derhuerst/vbb-hafas/issues
- [ ] https://github.com/derhuerst/db-hafas/issues

**Comment by derhuerst** [comment]
- [ ] extract https://github.com/derhuerst/hafas-client/blob/079964ee400f4ba56e201f1db6195949f605f38f/parse/location.js#L12-L13 into `parse/coord.js`

**Comment by derhuerst** [comment]
- [ ] https://github.com/schildbach/public-transport-enabler/commit/7117f9e933c7301a476717791cc2a75a038d514b
- [ ] https://github.com/schildbach/public-transport-enabler/commit/651557ba0c03d9278e1194a03994f5046d10482d
- [ ] https://github.com/schildbach/public-transport-enabler/commit/3a053c517d839a093dc3b71848cc19d9391fe025
- [ ] https://github.com/schildbach/public-transport-enabler/commit/760d373065c0e66584bf4f0a8b2395cf6e8d7287
- [ ] https://github.com/schildbach/public-transport-enabler/commit/f2ce4dd5245e50f7bcfd894d387725db775ba3be
- [ ] https://github.com/schildbach/public-transport-enabler/commit/a29613c0c4b0341e9f4e4351cc5ecf72357b8669
- [ ] https://github.com/schildbach/public-transport-enabler/commit/61ecf26077e31dba54cf001c10cdc3836c193362
- [ ] https://github.com/schildbach/public-transport-enabler/commit/d85f0b80b5630f5d461c295bf9a575f0f5312729
- [ ] https://github.com/schildbach/public-transport-enabler/commit/3613ddc06add3c113f0680f72fe41dfeb332d7fa

**Comment by derhuerst** [comment]
- [ ] consider implementing https://github.com/schildbach/public-transport-enabler/commit/e3076480537f8c1620f09b5d9e7318b4e7448f9f

**Comment by derhuerst** [comment]
@juliuste new DB Navigator features

![IMG_4526](https://user-images.githubusercontent.com/5072613/59382610-6f952b80-8d5e-11e9-80fd-67482646e9a6.jpg)
![IMG_5163](https://user-images.githubusercontent.com/5072613/59382618-7328b280-8d5e-11e9-9277-af5779bc611f.jpg)

**Comment by derhuerst** [comment]
https://gist.github.com/derhuerst/7bac4d957977fe52d59307f39559125c#file-1-locations-http-L40-L51
